appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: QJxZGYA3Fp70/nc0BHFfTK05XBd854laHqkYbmE/4IWT9IYVofvZBXVqWYGa1juvWH2aukxhBAeki2PBqBX2Iup3kX0oraW3ue7Q9Z7AG/ezRQdfU50UsSwduJxUHR+JbAzMxqcAqoJe3MEdNENBxS2T5GuJRLAhkd/HL6h+5IrOmz4qHAk7Dvt6E7ZNMLiaJqWi3int/XAGmyi7PRIBkAqxzUz+GgSQBA6CSc7GDFxTJrQNypxOYoPo0Kohc88jEsjbySISvrJZVoi+EV+X10s/ziGTwLgsdZoTn+RwH//UGTDziO/+TNcQygRDs9k8pIeDPUfCRbS86GLVG9hTerooY9yTZJk0DtsaYRNoSMYucTu25JBxxyXgNi+a8ZrM3L4bTZS/SwGc8bzIRapRnquJNdNfnSTSyvMfM/CRk8mLDvYitpWd63mLEYaxpftnqgxddJ+I9Oopzp2xRpRjFQxC/lY73FqdpJBM3awFxViBzlDIvf3HWgGMvvGRUFwPxqmLw3QTwA4Nag4pGUwgchBT9vnTXAczyYRJdWz5QPCIELZUN88KgfBU9ExnV/HCI1NWhp93m73pJXTUNL+R+m9qcUR6Q4BDP23E/q8NcZtCoEIRJyZeO/fvDkUiSht0HRKIVmlpILHRxWRWhDgGLq8/vuogEvDu72j37q1Ge40=
conda_forge_output_validation: true
